name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Dry run publish voprf-ng
        run: cargo publish --dry-run --manifest-path Cargo.toml

      - name: Publish voprf-ng
        run: cargo publish --manifest-path Cargo.toml
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}
